[package]
name = 'jsdotlua/react-devtools-shared'
description = 'https://github.com/grilme99/CorePackages'
version = '17.0.2'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
LuauPolyfill = 'jsdotlua/luau-polyfill@1.2.3'
React = 'jsdotlua/react@17.0.2'
ReactDebugTools = 'jsdotlua/react-debug-tools@17.0.2'
ReactIs = 'jsdotlua/react-is@17.0.2'
ReactReconciler = 'jsdotlua/react-reconciler@17.0.2'
ReactRoblox = 'jsdotlua/react-roblox@17.0.2'
Shared = 'jsdotlua/shared@17.0.2'
