[package]
name = 'jsdotlua/react-roblox'
description = 'https://github.com/grilme99/CorePackages'
version = '17.0.2'
license = 'MIT + Apache 2.0'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
LuauPolyfill = 'jsdotlua/luau-polyfill@1.2.3'
React = 'jsdotlua/react@17.0.2'
ReactReconciler = 'jsdotlua/react-reconciler@17.0.2'
Scheduler = 'jsdotlua/scheduler@17.0.2'
Shared = 'jsdotlua/shared@17.0.2'
