[package]
name = 'jsdotlua/react-test-renderer'
description = 'React Test Renderer'
version = '17.0.1'
license = 'MIT'
authors = ['Meta Platforms']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
LuauPolyfill = 'jsdotlua/luau-polyfill@1.2.3'
Shared = 'jsdotlua/shared@17.0.1-rc.19'
Scheduler = 'jsdotlua/scheduler@17.0.1-rc.19'
Reconciler = 'jsdotlua/react-reconciler@17.0.1-rc.19'
