[package]
name = 'jsdotlua/react'
description = 'https://github.com/grilme99/CorePackages'
version = '0.12.0'
license = 'MIT + Apache 2.0'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
LuauPolyfill = 'jsdotlua/luau-polyfill@1.2.3'
Shared = 'jsdotlua/shared@17.0.1-rc.19'
