[package]
name = 'jsdotlua/react-is'
description = 'https://github.com/grilme99/CorePackages'
version = '17.0.2'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
Shared = 'jsdotlua/shared@17.0.2'
